
export const metrics = [
  { key: 'tpr', name: 'Tasa de Verdaderos Positivos' },
  { key: 'tnr', name: 'Tasa de Verdaderos Negativos' },
  { key: 'for', name: 'Tasa de Falsas Omisiones' },
  { key: 'fdr', name: 'Tasa de Falsos Descubrimientos' },
  { key: 'fpr', name: 'Tasa de Falsos Positivos' },
  { key: 'fnr', name: 'Tasa de Falsos Negativos' },
  { key: 'npv', name: 'Valor Predictivo Negativo' },
  { key: 'precision', name: 'Precisión' },
  { key: 'ppr', name: 'Proporción de Positivos Predichos' },
  { key: 'pprev', name: 'Prevalencia Predicha' },
  { key: 'prev', name: 'Prevalencia' },
];

export const metrics_bias = [
    { key: 'ppr_disparity', name: 'Disparidad de Proporción de Positivos Predichos' },
    { key: 'pprev_disparity', name: 'Disparidad de Prevalencia Predicha' },
    { key: 'precision_disparity', name: 'Disparidad de Precisión' },
    { key: 'fdr_disparity', name: 'Disparidad de Tasa de Falsos Descubrimientos' },
    { key: 'for_disparity', name: 'Disparidad de Tasa de Falsas Omisiones' },
    { key: 'fpr_disparity', name: 'Disparidad de Tasa de Falsos Positivos' },
    { key: 'fnr_disparity', name: 'Disparidad de Tasa de Falsos Negativos' },
    { key: 'tpr_disparity', name: 'Disparidad de Tasa de Verdaderos Positivos' },
    { key: 'tnr_disparity', name: 'Disparidad de Tasa de Verdaderos Negativos' },
    { key: 'npv_disparity', name: 'Disparidad de Valor Predictivo Negativo' },
    { key: 'accuracy_disparity', name: 'Disparidad de Exactitud' },
];

export const METRIC_TRANSLATIONS: { [key: string]: string } = {
    'model_id': 'ID del Modelo',
    'score_threshold': 'Umbral de Puntuación',
    'k': 'Valor K',
    'attribute_name': 'Atributo Protegido',
    'attribute_value': 'Valor del Atributo',
    'pp': 'Casos Predichos Positivos',
    'pn': 'Casos Predichos Negativos',
    'fp': 'Casos Falsos Positivos',
    'fn': 'Casos Falsos Negativos',
    'tn': 'Casos Verdaderos Negativos',
    'tp': 'Casos Verdaderos Positivos',
    'group_label_pos': 'Etiquetas Positivas del Grupo',
    'group_label_neg': 'Etiquetas Negativas del Grupo',
    'group_size': 'Tamaño del Grupo',
    'total_entities': 'Total de Entidades',
    'prev': 'Prevalencia Observada',
    'pprev': 'Prevalencia Predicha',
    'accuracy': 'Exactitud General',
    'tpr': 'Tasa de Verdaderos Positivos (TPR)',
    'tnr': 'Tasa de Verdaderos Negativos (TNR)',
    'for': 'Tasa de Falsas Omisiones (FOR)',
    'fdr': 'Tasa de Falsos Descubrimientos (FDR)',
    'fpr': 'Tasa de Falsos Positivos (FPR)',
    'fnr': 'Tasa de Falsos Negativos (FNR)',
    'npv': 'Valor Predictivo Negativo (NPV)',
    'precision': 'Precisión (PPV)',
    'ppr': 'Proporción Predicha Positiva (PPR)',
    'ppr_disparity': 'Disparidad en Proporción de Predichos Positivos (PPR)',
    'pprev_disparity': 'Disparidad en Prevalencia Predicha',
    'precision_disparity': 'Disparidad en Precisión (PPV)',
    'fdr_disparity': 'Disparidad en Tasa de Falsos Descubrimientos (FDR)',
    'for_disparity': 'Disparidad en Tasa de Falsas Omisiones (FOR)',
    'fpr_disparity': 'Disparidad en Tasa de Falsos Positivos (FPR)',
    'fnr_disparity': 'Disparidad en Tasa de Falsos Negativos (FNR)',
    'tpr_disparity': 'Disparidad en Tasa de Verdaderos Positivos (TPR)',
    'tnr_disparity': 'Disparidad en Tasa de Verdaderos Negativos (TNR)',
    'npv_disparity': 'Disparidad en Valor Predictivo Negativo (NPV)',
    'accuracy_disparity': 'Disparidad en Exactitud General',
    'fairness_conclusion': 'Conclusión de Equidad',
    'Statistical Parity': 'Paridad Estadística',
    'Impact Parity': 'Paridad de Impacto Dispar',
    'FDR Parity': 'Paridad en Tasa de Falsos Descubrimientos (FDR)',
    'FOR Parity': 'Paridad en Tasa de Falsas Omisiones (FOR)',
    'FPR Parity': 'Paridad en Tasa de Falsos Positivos (FPR)',
    'FNR Parity': 'Paridad en Tasa de Falsos Negativos (FNR)',
    'TPR Parity': 'Paridad en Tasa de Verdaderos Positivos (TPR)',
    'TNR Parity': 'Paridad en Tasa de Verdaderos Negativos (TNR)',
    'NPV Parity': 'Paridad en Valor Predictivo Negativo (NPV)',
    'Precision Parity': 'Paridad en Precisión (PPV)',
    'Accuracy Parity': 'Paridad en Exactitud General',
    // Nuevas entradas para valores de referencia
    'ppr_ref_group_value': 'Valor de Referencia PPR',
    'pprev_ref_group_value': 'Valor de Referencia Prevalencia Predicha',
    'precision_ref_group_value': 'Valor de Referencia Precisión (PPV)',
    'fdr_ref_group_value': 'Valor de Referencia FDR',
    'for_ref_group_value': 'Valor de Referencia FOR',
    'fpr_ref_group_value': 'Valor de Referencia FPR',
    'fnr_ref_group_value': 'Valor de Referencia FNR',
    'tpr_ref_group_value': 'Valor de Referencia TPR',
    'tnr_ref_group_value': 'Valor de Referencia TNR',
    'npv_ref_group_value': 'Valor de Referencia NPV',
};