
export const metrics = [
  { key: 'tpr', name: 'Tasa de Verdaderos Positivos' },
  { key: 'tnr', name: 'Tasa de Verdaderos Negativos' },
  { key: 'for', name: 'Tasa de Falsas Omisiones' },
  { key: 'fdr', name: 'Tasa de Falsos Descubrimientos' },
  { key: 'fpr', name: 'Tasa de Falsos Positivos' },
  { key: 'fnr', name: 'Tasa de Falsos Negativos' },
  { key: 'npv', name: 'Valor Predictivo Negativo' },
  { key: 'precision', name: 'Precisión' },
  { key: 'ppr', name: 'Proporción de Positivos Predichos' },
  { key: 'pprev', name: 'Prevalencia Predicha' },
  { key: 'prev', name: 'Prevalencia' },
];

export const metrics_bias = [
    { key: 'ppr_disparity', name: 'Disparidad de Proporción de Positivos Predichos' },
    { key: 'pprev_disparity', name: 'Disparidad de Prevalencia Predicha' },
    { key: 'precision_disparity', name: 'Disparidad de Precisión' },
    { key: 'fdr_disparity', name: 'Disparidad de Tasa de Falsos Descubrimientos' },
    { key: 'for_disparity', name: 'Disparidad de Tasa de Falsas Omisiones' },
    { key: 'fpr_disparity', name: 'Disparidad de Tasa de Falsos Positivos' },
    { key: 'fnr_disparity', name: 'Disparidad de Tasa de Falsos Negativos' },
    { key: 'tpr_disparity', name: 'Disparidad de Tasa de Verdaderos Positivos' },
    { key: 'tnr_disparity', name: 'Disparidad de Tasa de Verdaderos Negativos' },
    { key: 'npv_disparity', name: 'Disparidad de Valor Predictivo Negativo' },
    { key: 'accuracy_disparity', name: 'Disparidad de Exactitud' },
];

export const METRIC_TRANSLATIONS: { [key: string]: string } = {
    'model_id': 'ID Modelo',
    'score_threshold': 'Umbral Score',
    'k': 'k',
    'attribute_name': 'Atributo',
    'attribute_value': 'Valor Atributo',
    'pp': 'Predichos Positivos',
    'pn': 'Predichos Negativos',
    'fp': 'Falsos Positivos',
    'fn': 'Falsos Negativos',
    'tn': 'Verdaderos Negativos',
    'tp': 'Verdaderos Positivos',
    'group_label_pos': 'Etiquetas Positivas Grupo',
    'group_label_neg': 'Etiquetas Negativas Grupo',
    'group_size': 'Tamaño Grupo',
    'total_entities': 'Total Entidades',
    'prev': 'Prevalencia',
    'pprev': 'Prevalencia Predicha',
    'accuracy': 'Exactitud',
    'tpr': 'Tasa Verdaderos Positivos (TPR)',
    'tnr': 'Tasa Verdaderos Negativos (TNR)',
    'for': 'Tasa Falsas Omisiones (FOR)',
    'fdr': 'Tasa Falsos Descubrimientos (FDR)',
    'fpr': 'Tasa Falsos Positivos (FPR)',
    'fnr': 'Tasa Falsos Negativos (FNR)',
    'npv': 'Valor Predictivo Negativo (NPV)',
    'precision': 'Precisión',
    'ppr': 'Proporción Predicha Positiva (PPR)',
    'ppr_disparity': 'Disparidad PPR',
    'pprev_disparity': 'Disparidad PPREV',
    'precision_disparity': 'Disparidad Precisión',
    'fdr_disparity': 'Disparidad FDR',
    'for_disparity': 'Disparidad FOR',
    'fpr_disparity': 'Disparidad FPR',
    'fnr_disparity': 'Disparidad FNR',
    'tpr_disparity': 'Disparidad TPR',
    'tnr_disparity': 'Disparidad TNR',
    'npv_disparity': 'Disparidad NPV',
    'accuracy_disparity': 'Disparidad Exactitud',
    'fairness_conclusion': 'Conclusión Equidad',
    'Statistical Parity': 'Paridad Estadística',
    'Impact Parity': 'Paridad de Impacto',
    'FDR Parity': 'Paridad FDR',
    'FOR Parity': 'Paridad FOR',
    'FPR Parity': 'Paridad FPR',
    'FNR Parity': 'Paridad FNR',
    'TPR Parity': 'Paridad TPR',
    'TNR Parity': 'Paridad TNR',
    'NPV Parity': 'Paridad NPV',
    'Precision Parity': 'Paridad de Precisión',
    'Accuracy Parity': 'Paridad de Exactitud'
};